# Generated by Django 2.1.7 on 2019-03-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(unique=True, verbose_name='Number')),
                ('weight', models.SmallIntegerField(verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(unique=True, verbose_name='Number')),
                ('x', models.SmallIntegerField(verbose_name='X')),
                ('Y', models.SmallIntegerField(verbose_name='Y')),
                ('name', models.CharField(default='node', max_length=10, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='app.Node', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='link',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='app.Node', verbose_name='Target'),
        ),
    ]
