# Generated by Django 2.1.7 on 2019-03-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Level')),
                ('name', models.CharField(default='node', max_length=10, verbose_name='Name')),
                ('links', models.ManyToManyField(to='app.Link', verbose_name='Links')),
                ('nodes', models.ManyToManyField(related_name='graphs', to='app.Node', verbose_name='Nodes')),
            ],
        ),
    ]
