# Generated by Django 2.1.7 on 2019-03-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190321_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='Y',
            new_name='y',
        ),
    ]
