# Generated by Django 2.1.7 on 2019-03-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20190321_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Graph', verbose_name='Graph')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Link', verbose_name='Link')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLinkAdvanced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Weight')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Graph', verbose_name='Graph')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Link', verbose_name='Link')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.PositiveSmallIntegerField(verbose_name='Best Score')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Graph', verbose_name='Graph')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAdvances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Best Score')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='TimeStamp')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Graph', verbose_name='Graph')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
        ),
    ]
