# Generated by Django 2.1.7 on 2019-03-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playerlink_playerlinkadvanced_score_scoreadvances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreadvances',
            name='score',
            field=models.FloatField(verbose_name='Score'),
        ),
    ]
